# Package: Reference Standard M
# File:    .gitlab-ci.yml
# Summary: GitLab CI configuration
#
# SPDX-FileCopyrightText:  © 2020-2026 Fourth Watch Software LC
# SPDX-FileContributor:    David Wicksell <dlw@linux.com>
# SPDX-FileComment:        https://gitlab.com/Reference-Standard-M/rsm
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License (AGPL) as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

stages:
  - build
  - release
  - deploy

host-build:
  stage: build
  image: gcc:16.1.0
  script:
    - export USER=root
    - make -j
    - make install
    - rsm -v RSM -b 16 -s 16384 rsm.dat
    - rsm -j 2 rsm.dat
    - rsm -x 'open 1:("utils.rsm":"read") use 1 read code xecute code' rsm.dat
    - rsm -i rsm.dat
    - rsm -k rsm.dat
    - make uninstall
    - make clean

docker-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t rsm .
    - docker run -itd --name rsm rsm
    - sleep 5
    - docker exec rsm rsm -i
    - docker stop rsm
    - docker rm rsm
    - docker rmi rsm

version-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG != null && $CI_COMMIT_TAG !~ /-doc$/
  script:
    - sed -n "/^=== $CI_COMMIT_TAG/,/^=== v.*[^-pre]\.[0-9] -- /{/^=== $CI_COMMIT_TAG/{s/===/###/}; /^===/b; p}"
      CHANGELOG.adoc > ${CI_COMMIT_TAG}.md
    - sed -i '/^\[.*,.*\]/{N; N; N; N; s/^\[.*,\(.*\)\].*\n.*\n\(.*\)\n.*\n/```\1\n\2\n```/}'
      ${CI_COMMIT_TAG}.md
    - sed -i '/^\[.*/d; ${/^$/d}; s/\(http.*\)\[\(.*\)\]/[\2](\1)/'
      ${CI_COMMIT_TAG}.md
  release:
    tag_name: $CI_COMMIT_TAG
    name: "Reference Standard M $CI_COMMIT_TAG"
    description: ${CI_COMMIT_TAG}.md

pages:
  stage: deploy
  image: antora/antora:latest
  variables:
    GIT_DEPTH: 0
    GIT_STRATEGY: clone
  rules:
    - if: $CI_COMMIT_TAG != null && $CI_COMMIT_TAG =~ /-doc$/
  script:
    - npm install @antora/lunr-extension
    - mkdir public
    - antora generate --clean --redirect-facility=gitlab --to-dir=public etc/antora-playbook.yml
  artifacts:
    paths:
      - public
