stages:
  - build
  - release

host-build:
  stage: build
  image: gcc:12.2.0
  script:
    - export USER=root
    - make -j
    - make install
    - rsm -v TST -b 16 -s 16384 tst.dat
    - rsm -j 2 tst.dat
    - rsm -x 'open 1:("utils.rsm":"read") use 1 read code xecute code' tst.dat
    - rsm -i tst.dat
    - rsm -k tst.dat
    - make uninstall
    - make clean

docker-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t rsm .
    - docker run -itd --name rsm rsm
    - sleep 5
    - docker exec rsm rsm -i
    - docker stop rsm
    - docker rm rsm
    - docker rmi rsm

version-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - sed -n "/$CI_COMMIT_TAG/,/^===/"'{s/===/###/; /^\[.*,.*\]/{N; N; N; N; s/^\[.*,\(.*\)\].*\n.*\n\(.*\)\n.*\n/```\1\n\2\n```\n/}; /^\[.*/d; p}' CHANGELOG.adoc | sed '$d' | sed '$d' > ${CI_COMMIT_TAG}.md
  release:
    tag_name: $CI_COMMIT_TAG
    name: "Reference Standard M ${CI_COMMIT_TAG/v/V}"
    description: ${CI_COMMIT_TAG}.md
