# Package: Reference Standard M
# File:    doc/antora-playbook.yml
# Summary: Antora playbook configuration file
#
# SPDX-FileCopyrightText:  © 2024-2026 Fourth Watch Software LC
# SPDX-FileContributor:    David Wicksell <dlw@linux.com>
# SPDX-FileComment:        https://gitlab.com/Reference-Standard-M/rsm
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License (AGPL) as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

site:
  title: Reference Standard M Documentation
  url: https://reference-standard-m.gitlab.io/rsm
  start_page: docs::index.adoc

urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to

content:
  edit_url: false
  sources:
  - url: ~+
    tags: '*-doc'
    branches: ~
    start_path: doc

output:
  clean: true
  dir: public

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: doc/supplemental-ui
