////
Package: Reference Standard M
File:    doc/modules/ROOT/nav.adoc
Summary: Antora navigation source

SPDX-FileCopyrightText:  © 2024-2026 Fourth Watch Software LC
SPDX-FileContributor:    David Wicksell <dlw@linux.com>
SPDX-FileComment:        https://gitlab.com/Reference-Standard-M/rsm
SPDX-License-Identifier: GFDL-1.3-no-invariants-or-later

Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU Free Documentation License, Version 1.3 or any later
version published by the Free Software Foundation; with no Invariant
Sections, with no Front-Cover texts, and with no Back-Cover Texts.

You should have received a copy of the GNU Free Documentation License along
with this program. If not, see https://www.gnu.org/licenses/.
////

= Reference Standard M
Author: David Wicksell

* xref:language.adoc[Language Guide]
//* xref:database.adoc[Database Management Guide]
* xref:seqio.adoc[Sequential I/O Interface]
//* xref:xcall.adoc[External Call Interface]
//* xref:util.adoc[Supplemental Utilities]
* xref:web.adoc[Web Server Utility]
* xref:rsm.adoc[RSM(1) Manual Page]
* xref:upgrade.adoc[Database Upgrade Instructions]
* xref:conformance.adoc[Conformance Clause]
