////
Package: Reference Standard M
File:    doc/adoc/conformance.adoc
Summary: Conformance clause

David Wicksell <dlw@linux.com>
Copyright © 2021-2024 Fourth Watch Software LC
https://gitlab.com/Reference-Standard-M/rsm

Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU Free Documentation License, Version 1.3 or any later
version published by the Free Software Foundation; with no Invariant
Sections, with no Front-Cover texts, and with no Back-Cover Texts.

You should have received a copy of the GNU Free Documentation License along
with this program. If not, see https://www.gnu.org/licenses/.

SPDX-FileCopyrightText:  © 2021 David Wicksell <dlw@linux.com>
SPDX-License-Identifier: GFDL-1.3-no-invariants-or-later
////

= Conformance Clause

== Summary

Reference Standard M Version 1.81.0 conforms to ANSI/MDC X11.1-1995
(ISO/IEC 11756:1999) with the following exceptions (there may be more):

* Supports up to 32 uniquely distinguished characters in names, rather than 8
* Supports lower case alphabetic characters in names, not just upper case
* Returns an error (`M56`) with longer names, rather than truncating them
* Only supports the M character set profile
* Transaction processing is not implemented
* A comment can start in the first column
* Local and global variables are restricted to a maximum of 63 subscripts
* Does not support name indirection in `for`
* Supports some forms of expression indirection
* Routine references do not support environments (extended references)
* `$NEXT` is supported by default, but can be disabled
* `OPEN` does not always acquire exclusive access of devices
* `CLOSE` device parameters are not implemented (allowed by standard)
* `JOB` process parameters are not implemented (allowed by standard)
* `HANG 0` is not ignored, it gives up the process timeslice
* `SET` evaluates the expression on the right-hand side of the '`=`' before it
  evaluates the subscripts on the left-hand side of the '`=`'
* `$INCREMENT` is implemented
* Reverse `$QUERY` is implemented
* Use of `$QUERY` does not result in the naked indicator and `$REFERENCE`
  becoming empty, it behaves like `$ORDER`
* `$DEVICE` may not be set
* `$STORAGE` does not return the number of characters of free space remaining,
  it returns the number of free local variable slots in the symbol table
* The uniqueness of `$SYSTEM` is only guaranteed by compiler build macros, so
  may not be unique under certain conditions
* `^$CHARACTER` does not include a `"PATCODE"` node or algorithm
* `^$GLOBAL` includes extra nodes
* `^$JOB` includes extra nodes
* `^$ROUTINE` includes extra nodes
* `^$SYSTEM` includes many extra nodes, and does not use as its first subscript
  the contents of `$SYSTEM`

See the xref:language.adoc[Language Guide] for more information on how each
language element conforms to the standard.
