# Package: Reference Standard M
# File:    snap/snapcraft.yaml
# Summary: Snap configuration
#
# SPDX-FileCopyrightText:  © 2026 Fourth Watch Software LC
# SPDX-FileContributor:    David Wicksell <dlw@linux.com>
# SPDX-FileComment:        https://gitlab.com/Reference-Standard-M/rsm
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License (AGPL) as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

name: rsm
title: Reference Standard M
icon: snap/gui/rsm-logo.png
adopt-info: rsm
license: AGPL-3.0-or-later
contact: dlw@linux.com
source-code: https://gitlab.com/reference-standard-m/rsm
issues: https://gitlab.com/reference-standard-m/rsm/-/issues
website: https://rsmlang.com/
donation: https://www.paypal.biz/fwslc
summary: An implementation of the M programming language and database
description: |
  Reference Standard M (RSM) is an implementation of the M programming
  language and database, which implements the latest M standard that has
  been released by the M Development Committee (MDC), currently
  ANSI/MDC X11.1-1995 (ISO/IEC 11756:1999).

  This is the post-relational database.

base: core26
grade: stable
confinement: strict
compression: xz
platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  riscv64:
  s390x:

parts:
  rsm:
    plugin: make
    source: .
    source-type: local
    build-packages:
      - libcrypt-dev
      - git
    build-environment:
      - RSM_BUILD: all
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags | grep -o 'v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*')
    override-build: |
      make -j prefix=/usr $RSM_BUILD
      make prefix=/usr install DESTDIR=$CRAFT_PART_INSTALL
      make prefix=/usr install-docs DESTDIR=$CRAFT_PART_INSTALL
      install -D -m 755 $CRAFT_PROJECT_DIR/snap/local/rsm.wrapper $CRAFT_PART_INSTALL/usr/bin/rsm.wrapper
      install -D -m 755 $CRAFT_PROJECT_DIR/snap/local/rsm.daemon $CRAFT_PART_INSTALL/usr/bin/rsm.daemon
      install -D -m 755 $CRAFT_PROJECT_DIR/snap/local/rsm.man $CRAFT_PART_INSTALL/usr/bin/rsm.man

  mandoc:
    plugin: nil
    stage-packages:
      - mandoc
    prime:
      - usr/bin/mandoc

apps:
  rsm:
    command: usr/bin/rsm.wrapper
    environment:
      RSM_DBFILE: $SNAP_COMMON/rsm.dat
    plugs:
      - home
      - removable-media
      - network
      - network-bind

  daemon:
    command: usr/bin/rsm.daemon
    daemon: forking
    stop-command: usr/bin/rsm -k
    stop-mode: sigint
    restart-condition: on-failure
    environment:
      RSM_DBFILE: $SNAP_COMMON/rsm.dat

  man:
    command: usr/bin/rsm.man
