#!/bin/sh
#
# Package: Reference Standard M
# File:    snap/hooks/post-refresh
# Summary: Snap post-refresh hook for rsm
#
# SPDX-FileCopyrightText:  © 2026 Fourth Watch Software LC
# SPDX-FileContributor:    David Wicksell <dlw@linux.com>
# SPDX-FileComment:        https://gitlab.com/Reference-Standard-M/rsm
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License (AGPL) as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
# General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

rsmdb="$(snapctl get database-file 2>/dev/null)"
rsmdb="${rsmdb:-$SNAP_COMMON/rsm.dat}"

$SNAP/usr/bin/rsm -j 1 -U "${rsmdb}"
$SNAP/usr/bin/rsm -x "open 1:(\"$SNAP/usr/share/rsm/utils.rsm\":\"read\") use 1 read code xecute code" "${rsmdb}"
$SNAP/usr/bin/rsm -k "${rsmdb}"

exit 0

# ex: filetype=sh
